version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:39
    # name: 'registry.redhat.io/ansible-automation-platform-24/de-minimal-rhel8:latest'

dependencies:
  python_interpreter:
    package_system: "python310"
    python_path: "/usr/bin/python3.10"
  ansible_core:
    package_pip: ansible-core==2.16.2
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  galaxy: ansible-collections.yml
  python: python-packages.txt
  system: system-packages.txt

options:
  package_manager_path: /usr/bin/dnf
  user: root

additional_build_steps:
  prepend_base:
    - RUN useradd -u 1000 -m ansible
    - RUN echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    - RUN dnf install -y which python-argcomplete
    - RUN dnf install -y zip unzip
  prepend_final:
    - RUN $PYCMD -m pip install --upgrade pip setuptools
    - RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - RUN unzip awscliv2.zip
    - RUN ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
    - RUN rm -rf awscliv2.zip
    # Install kubectl
    - RUN curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - RUN rm kubectl
